version: "3.8"
services:
  app:
    container_name: api
    build:
      context: ./api
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - api
